# Generated by Django 6.0 on 2026-08-23 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_departmenthierarchy_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=3, verbose_name='優先度'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='departmenthierarchy',
            constraint=models.CheckConstraint(condition=models.Q(('parent_department', models.F('department')), _negated=True), name='department_hierarchy_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(fields=('employee', 'department'), name='unique_employee_department'),
        ),
        migrations.AddConstraint(
            model_name='managementgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('is_admin', True), ('permission_set_id__isnull', True)), models.Q(('department__isnull', False), ('is_admin', False), ('permission_set_id__isnull', False)), _connector='OR'), name='management_group_admin_consistency'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='task_priority_range'),
        ),
    ]
