# Generated by Django 6.0 on 2026-09-24 14:03

import app.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_task_description_alter_task_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='managementgroup',
            name='management_group_admin_consistency',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[app.validators.validate_description_contains_issue_reference], verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='優先度'),
        ),
        migrations.AddConstraint(
            model_name='managementgroup',
            constraint=models.CheckConstraint(condition=models.Q(('is_admin', False), ('department__isnull', True), _connector='OR'), name='management_group_admin_without_department', violation_error_message='全社管理者グループには部門を設定できません。'),
        ),
        migrations.AddConstraint(
            model_name='managementgroup',
            constraint=models.CheckConstraint(condition=models.Q(('is_admin', True), ('department__isnull', False), _connector='OR'), name='management_group_non_admin_requires_department', violation_error_message='全社管理者でない場合は部門の設定が必須です。'),
        ),
        migrations.AddConstraint(
            model_name='managementgroup',
            constraint=models.CheckConstraint(condition=models.Q(('is_admin', False), ('permission_set_id__isnull', True), _connector='OR'), name='management_group_admin_without_permission_set', violation_error_message='全社管理者グループには権限セットを設定できません。'),
        ),
        migrations.AddConstraint(
            model_name='managementgroup',
            constraint=models.CheckConstraint(condition=models.Q(('is_admin', True), ('permission_set_id__isnull', False), _connector='OR'), name='management_group_non_admin_requires_permission_set', violation_error_message='全社管理者でない場合は権限セットの設定が必須です。'),
        ),
    ]
