# Generated by Django 6.0 on 2026-10-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_django_standard_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '会社', 'verbose_name_plural': '会社'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員'},
        ),
        migrations.AlterModelOptions(
            name='managementgroup',
            options={'verbose_name': '管理グループ', 'verbose_name_plural': '管理グループ'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'タスク', 'verbose_name_plural': 'タスク'},
        ),
    ]
