# Generated by Django 6.0 on 2026-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_django_standard_validation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='unique_primary_department_per_employee', violation_error_message='この社員には既に主務の部門があります。'),
        ),
        migrations.AlterConstraint(
            model_name='employeedepartment',
            name='unique_employee_department',
            constraint=models.UniqueConstraint(fields=('employee', 'department'), name='unique_employee_department', violation_error_message='この社員は既にこの部門に所属しています。'),
        ),
    ]
